"""initial schema

Revision ID: f66a7128cab1
Revises:
Create Date: 2026-04-23 08:52:44.950448

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f66a7128cab1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_call_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_api_call_log_source_ts", "api_call_log", ["source", "ts"], unique=False)
    op.create_table(
        "tokens",
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_username", sa.Text(), nullable=True),
        sa.Column("language_code", sa.Text(), server_default="en", nullable=True),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column("timezone", sa.Text(), server_default="UTC", nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    # Plan to partition price_snapshots by day in a future migration once row
    # count exceeds ~10M. Read pattern: latest N rows per token_address.
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("token_address", sa.Text(), nullable=False),
        sa.Column("market_cap_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("volume_5m_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("liquidity_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("holder_count", sa.Integer(), nullable=True),
        sa.Column("source", sa.Text(), server_default="pumpfun", nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["token_address"], ["tokens.address"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_snapshots_token_address"), "price_snapshots", ["token_address"], unique=False
    )
    op.create_index(
        "ix_price_snapshots_token_ts",
        "price_snapshots",
        ["token_address", "ts"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(op.f("ix_price_snapshots_ts"), "price_snapshots", ["ts"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_address", sa.Text(), nullable=False),
        sa.Column("growth_threshold_pct", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("stoploss_threshold_pct", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "warning_buffer_pct",
            sa.Numeric(precision=8, scale=2),
            server_default="5.00",
            nullable=False,
        ),
        sa.Column(
            "volume_spike_k",
            sa.Numeric(precision=4, scale=2),
            server_default="3.00",
            nullable=False,
        ),
        sa.Column("baseline_market_cap", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("priority", sa.String(length=16), server_default="high", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('high', 'medium', 'low', 'paused')", name="ck_subscriptions_priority"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'stopped', 'archived')", name="ck_subscriptions_status"
        ),
        sa.ForeignKeyConstraint(["token_address"], ["tokens.address"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "token_address", name="uq_subscriptions_user_token"),
    )
    op.create_index(
        op.f("ix_subscriptions_token_address"), "subscriptions", ["token_address"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "alerts_sent",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("alert_type", sa.String(length=32), nullable=False),
        sa.Column("triggered_at_market_cap", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("delivered", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("delivery_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "alert_type IN ("
            "'growth_hit', 'growth_warning', 'stoploss_hit', "
            "'stoploss_warning', 'volume_spike'"
            ")",
            name="ck_alerts_sent_alert_type",
        ),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_alerts_sent_subscription_created",
        "alerts_sent",
        ["subscription_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_alerts_sent_subscription_created", table_name="alerts_sent")
    op.drop_table("alerts_sent")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_token_address"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_price_snapshots_ts"), table_name="price_snapshots")
    op.drop_index(
        "ix_price_snapshots_token_ts", table_name="price_snapshots", postgresql_using="btree"
    )
    op.drop_index(op.f("ix_price_snapshots_token_address"), table_name="price_snapshots")
    op.drop_table("price_snapshots")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("tokens")
    op.drop_index("ix_api_call_log_source_ts", table_name="api_call_log")
    op.drop_table("api_call_log")
    # ### end Alembic commands ###
